### ISSUE TITLE
Dual App Creation!

### ISSUE THREAD

**Issue by Sahilkumr** [artcodefun/launcher_icon_switcher#3]
While Almost Everything is Working fine.
The Only Issue is We have **Two Same App** Icon in our App list. Which Is Kind of Weird.
We Can Disable the **.MainActvity** Class Component Also, so that there's only.
! [launcher_icon_switcher_dual_app](https://github.com/artcodefun/launcher_icon_switcher/assets/153812803/e01f284a-c0a2-4025-a6ba-26f60a214ccc)

**Comment by artcodefun** [comment]
Hello, @Sahilkumr !
As you can see in [android platform setup](https://github.com/artcodefun/launcher_icon_switcher?tab=readme-ov-file#platform-setup) it is recommended to disable your main activity in the AndroidManifest.xml, otherwise the android OS will create a launcher icon for each active component with `intent-filter` of `android.intent.category.LAUNCHER` category. Alternatively you can keep your activity enabled and just remove `<category android:name="android.intent.category.LAUNCHER"/>` from its `intent-filter`

**Comment by Sahilkumr** [comment]
> Hello, @Sahilkumr ! As you can see in [android platform setup](https://github.com/artcodefun/launcher_icon_switcher?tab=readme-ov-file#platform-setup) it is recommended to disable your main activity in the AndroidManifest.xml, otherwise the android OS will create a launcher icon for each active component with `intent-filter` of `android.intent.category.LAUNCHER` category. Alternatively you can keep your activity enabled and just remove `<category android:name="android.intent.category.LAUNCHER"/>` from its `intent-filter`

U r Right, that should Have Worked.
But It's Not Working Bro!! 
Still, We Get Two Similar Icons: Dual App

**Comment by Sahilkumr** [comment]
So, Finally I Have Come With a Idea and Its Working Perfectly.
Firstly 
**Method : 1**
don't Disable MainActivity.
-- Instead Create an Extra Icon Image with the Same Main Activity Name
-- and add it to the List of Icons.
-- thus, no copy App Icon Will be Created in App List.
**Method : 2**
-- Disable MainActivity from the Native Code
-- that using the PackagerManager -> setComponentEnabledSetting.
